config/routes.rb
RailsNaPraiaDuvidas::Application.routes.draw do
  resources :entidade2s


  resources :entidade1s


  resources :answers
  resources :questions
  resources :badges

  get "home/index"
  match 'users/:user_id', to: 'users#index'
  match 'answers/:question_id/new', to: 'answers#new'
  match 'vote/:answer_id/:type', to: 'answers#vote'
  match 'votes' , to: 'questions#votes_count'

  match 'login', to: 'home#login'
  match 'login/:provider', to: 'sessions#login'
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('http://www.google.com.br')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'home#index'

end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :content, type: String
  field :hits, type: Integer

  has_many :answers
  belongs_to :user

  def hit
    if self.hits==nil
      self.hits=0
    end
    self.hits+=1
    save
  end

  def votes
    votes = 0
    self.answers.each do |a|
      votes += a.votes.count
    end
    return votes
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    @question.hit
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])
    @question.user = current_user
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  def votes_count()
    json = []
    
    questions = Question.all
    questions.each do |q|
      json.push({"id" => q.id.to_s , "votes" => q.votes}) 


    end

      render :layout => nil , :json => json
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_field' %>
    </div>
  </div>
 
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                questions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:_type) %></th>
      <th><%= model_class.human_attribute_name(:_id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:hits) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.id, question_path(question) %></td>
        <td><%= question._type %></td>
        <td><%= question._id %></td>
        <td><%= question.title %></td>
        <td><%= question.content %></td>
        <td><%= question.hits %></td>
        <td><%=l question.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_question_path(question), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      question_path(question),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_question_path,
            :class => 'btn btn-primary' %>

app/views/questions/new.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Nova Pergunta") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1>
    <img src="<%=@question.user.image_url%>" class="img-polaroid" width="64" height="64">
    <%= @question.title %>
  </h1>
  <div class="img-polaroid question-content">
    <%= raw markdown(@question.content) %>
  </div>
</div>

<style type="text/css">
  .answer-content {
    padding-top: 1em;
    padding-left: 1em;
  }
  .question-content {
    padding-top: 1em;
    padding-left: 1em;
    font-size: 16px;
  }
  .answer-vote-balance {
    font-size: 16px;
    font-weight: bold;
  }
</style>

<% @question.answers.each do |a|%>
  <div>
    <img src="<%=a.user.image_url%>" class="img-polaroid" width="32" height="32">
    <%= image_tag 'up_32.png',class: 'up-vote', data: a.id %>
    <span id="answer-balance-<%=a.id%>" class="answer-vote-balance"><%= a.vote_balance %></span>
    <%= image_tag 'down_32.png',class: 'down-vote', data: a.id %>
  </div>
  <div class="img-polaroid">
    <div class="answer-content">
      <%= raw markdown(a.content) %>
    </div>
  </div>
  <br>
<% end%>

<div class="form-actions">
  <% if current_user!=nil && @question.user.id==current_user.id%>
    <%= link_to 'Responder',"/answers/#{@question.id}/new", :class => 'btn btn-success'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_question_path(@question), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                question_path(@question),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Responder',"/login?question_id=#{@question.id}", :class => 'btn'  %>
  <% end %>
</div>