config/routes.rb
RailsNaPraiaDuvidas::Application.routes.draw do
  resources :entidade2s


  resources :entidade1s


  resources :answers
  resources :questions
  resources :badges

  get "home/index"
  match 'users/:user_id', to: 'users#index'
  match 'answers/:question_id/new', to: 'answers#new'
  match 'vote/:answer_id/:type', to: 'answers#vote'
  match 'votes' , to: 'questions#votes_count'

  match 'login', to: 'home#login'
  match 'login/:provider', to: 'sessions#login'
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('http://www.google.com.br')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'home#index'

end

app/models/badge.rb
class Badge
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :logo, type: String
  field :rule, type: String
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @badges }
    end
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
    @badge = Badge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/new
  # GET /badges/new.json
  def new
    @badge = Badge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/1/edit
  def edit
    @badge = Badge.find(params[:id])
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(params[:badge])

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render json: @badge, status: :created, location: @badge }
      else
        format.html { render action: "new" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /badges/1
  # PUT /badges/1.json
  def update
    @badge = Badge.find(params[:id])

    respond_to do |format|
      if @badge.update_attributes(params[:badge])
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge = Badge.find(params[:id])
    @badge.destroy

    respond_to do |format|
      format.html { redirect_to badges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.erb
<%= form_for @badge, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :logo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :logo, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :rule, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rule, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                badges_path, :class => 'btn' %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<%- model_class = Badge -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/badges/index.html.erb
<%- model_class = Badge -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:logo) %></th>
      <th><%= model_class.human_attribute_name(:rule) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= link_to badge.name, badge_path(badge) %></td>
        <td><img src="<%= badge.logo %>" height="100" width="100"></td>
        <td><%= badge.rule %></td>
        <td><%=l(badge.created_at) if badge.created_at!=nil %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_badge_path(badge), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      badge_path(badge),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_badge_path,
            :class => 'btn btn-primary' %>

app/views/badges/new.html.erb
<%- model_class = Badge -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/badges/show.html.erb
<%- model_class = Badge -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:_type) %>:</strong></dt>
  <dd><%= @badge._type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:_id) %>:</strong></dt>
  <dd><%= @badge._id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @badge.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:logo) %>:</strong></dt>
  <dd><%= @badge.logo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rule) %>:</strong></dt>
  <dd><%= @badge.rule %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              badges_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_badge_path(@badge), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              badge_path(@badge),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>