config/routes.rb
RailsNaPraiaDuvidas::Application.routes.draw do
  resources :entidade2s


  resources :entidade1s


  resources :answers
  resources :questions
  resources :badges

  get "home/index"
  match 'users/:user_id', to: 'users#index'
  match 'answers/:question_id/new', to: 'answers#new'
  match 'vote/:answer_id/:type', to: 'answers#vote'
  match 'votes' , to: 'questions#votes_count'

  match 'login', to: 'home#login'
  match 'login/:provider', to: 'sessions#login'
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('http://www.google.com.br')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'home#index'

end

app/models/answer.rb
class Answer
  include Mongoid::Document
  field :content, type: String
  
  belongs_to :question
  belongs_to :user
  has_many :votes

  validates :content, :user, :question, :presence => true

  def vote(user,type)
    begin
      vote = Vote.find_by(:user=>user,:answer=>self)
    rescue Exception => e
      vote = Vote.new
      vote.user = user
      vote.answer = self
    end
    
    if type==:up
      vote.up=true
    else
      vote.up=false
    end
    vote.save
    return vote
  end

  def vote_balance
    balance=0
    self.votes.each do |v|
      if v.up
        balance+=1
      else
        balance-=1
      end
    end
    return balance
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def vote
    type = params[:type] # up/down
    answer = Answer.find(params[:answer_id])
    if type=='up'
      answer.vote(current_user,:up)
    elsif type=='down'
      answer.vote(current_user,:down)
    else
      render :text => 'Unknown vote type, use "up" or "down"'
      return
    end
    render :text => "#{answer.vote_balance}"
  end

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new
    @answer.question_id = session[:question_id] = params[:question_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])
    @answer.question_id = session[:question_id]
    @answer.user = current_user

    respond_to do |format|
      if @answer.save
        session[:question_id]=nil
        format.html { redirect_to @answer.question, notice: 'Resposta criada com sucesso!' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for @answer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit 'Responder', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                answers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/answers/index.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:_type) %></th>
      <th><%= model_class.human_attribute_name(:_id) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:question_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= link_to answer.id, answer_path(answer) %></td>
        <td><%= answer._type %></td>
        <td><%= answer._id %></td>
        <td><%= answer.content %></td>
        <td><%= answer.question_id %></td>
        <td><%=l answer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_answer_path(answer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      answer_path(answer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_answer_path,
            :class => 'btn btn-primary' %>

app/views/answers/new.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h3>Respondendo: "<%= @answer.question.title%>"</h3>
</div>
<%= render :partial => 'form' %>

app/views/answers/show.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:_type) %>:</strong></dt>
  <dd><%= @answer._type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:_id) %>:</strong></dt>
  <dd><%= @answer._id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @answer.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:question_id) %>:</strong></dt>
  <dd><%= @answer.question_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              answers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_answer_path(@answer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              answer_path(@answer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>